# Generated by Django 2.2.10 on 2021-04-16 10:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
import survey_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название опроса')),
                ('desc', models.CharField(max_length=255, null=True, verbose_name='Описание опроса')),
                ('start_date', models.DateTimeField(default=datetime.datetime(2021, 4, 16, 13, 33, 37, 851326), verbose_name='Дата старта опроса')),
                ('end_date', models.DateTimeField(default=datetime.datetime(2021, 4, 23, 13, 33, 37, 851326), verbose_name='Дата окончания опроса')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст вопроса')),
                ('type', models.CharField(max_length=30, validators=[survey_app.models.validateQuestionType], verbose_name='Тип вопроса')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey_app.Survey', verbose_name='Опрос')),
            ],
        ),
    ]
