# Generated by Django 2.2.10 on 2021-04-19 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('TEXT', 'TEXT'), ('CHOICE', 'CHOICE'), ('MULTIPLY_CHOICE', 'MULTIPLY_CHOICE')], max_length=30, verbose_name='Тип вопроса'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 26, 18, 41, 38, 306790), verbose_name='Дата окончания опроса'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 19, 18, 41, 38, 306741), verbose_name='Дата старта опроса'),
        ),
    ]
