# Generated by Django 2.2.10 on 2021-04-20 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0003_auto_20210419_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 27, 17, 17, 45, 668289), verbose_name='Дата окончания опроса'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 20, 17, 17, 45, 668237), verbose_name='Дата старта опроса'),
        ),
    ]
