# Generated by Django 2.2.10 on 2021-04-20 14:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0004_auto_20210420_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 27, 14, 32, 13, 405280, tzinfo=utc), verbose_name='Дата окончания опроса'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 20, 14, 32, 13, 405214, tzinfo=utc), verbose_name='Дата старта опроса'),
        ),
    ]
