# Generated by Django 2.2.10 on 2021-04-20 16:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0005_auto_20210420_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('token', models.CharField(max_length=64, verbose_name='token')),
            ],
        ),
        migrations.AlterField(
            model_name='survey',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 27, 16, 1, 41, 749445, tzinfo=utc), verbose_name='Дата окончания опроса'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 20, 16, 1, 41, 749380, tzinfo=utc), verbose_name='Дата старта опроса'),
        ),
    ]
