# Generated by Django 2.2.10 on 2021-04-20 16:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0006_auto_20210420_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='user_id',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='survey',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 27, 16, 45, 33, 262803, tzinfo=utc), verbose_name='Дата окончания опроса'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 20, 16, 45, 33, 262734, tzinfo=utc), verbose_name='Дата старта опроса'),
        ),
    ]
