# Generated by Django 2.2.10 on 2021-04-23 08:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0008_auto_20210422_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 30, 8, 8, 55, 694301, tzinfo=utc), verbose_name='Дата окончания опроса'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 23, 8, 8, 55, 694301, tzinfo=utc), verbose_name='Дата старта опроса'),
        ),
        migrations.DeleteModel(
            name='Option',
        ),
    ]
